config/routes.rb
Rails.application.routes.draw do
  resources :paginas

  get 'home/index'

  root to: 'home#index'
  devise_for :users
  resources :users
  resources :posts
  resources :admin
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
  extend FriendlyId
  friendly_id :titulo, use: :slugged
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  belongs_to :user
  friendly_id :titulo, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 2)
  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  before_action :set_pagina, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @paginas = Pagina.all
    respond_with(@paginas)
  end

  def show
    respond_with(@pagina)
  end

  def new
    @pagina = Pagina.new
    respond_with(@pagina)
  end

  def edit
  end

  def create
    @pagina = Pagina.new(pagina_params)
    flash[:notice] = 'Pagina was successfully created.' if @pagina.save
    respond_with(@pagina)
  end

  def update
    flash[:notice] = 'Pagina was successfully updated.' if @pagina.update(pagina_params)
    respond_with(@pagina)
  end

  def destroy
    @pagina.destroy
    respond_with(@pagina)
  end

  private
    def set_pagina
      @pagina = Pagina.friendly.find(params[:id])
    end

    def pagina_params
      params.require(:pagina).permit(:titulo, :conteudo)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :subtitulo, :img_titulo, :texto)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/index.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>RFDev</h1>
          <hr class="small">
          <span class="subheading">Programação, Linux e outros.</span>
        </div>
      </div>
    </div>
  </div>
</header>

<%= link_to "Novo Post", new_post_path %>
<%= link_to "Nova Pagina", new_pagina_path %>

app/views/home/index.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>RFDev</h1>
          <hr class="small">
          <span class="subheading">Programação, Linux e outros.</span>
        </div>
      </div>
    </div>
  </div>
</header>

<% @posts.order('id desc').each do |post| %>
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-preview">
          <%= link_to(post) do %>
            <h2 class="post-title">
              <%= post.titulo %>
            </h2>
            <h3 class="post-subtitle">
              <%= post.subtitulo %>
            </h3>
          <% end %>
          <p class="post-meta">Postado por <%= post.user.name %> em <%= post.created_at %></p>
        </div>
        <hr>
      </div>
    </div>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 text-center">
      <div class="digg_pagination">
        <%= will_paginate @posts, :container => false %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RFDev Blog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "RFDev Blog" %>">
    <meta name="thumbnail" content="<%= asset_path 'thumbnail.png' %>" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/monokai.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "RFDev", { controller: "/home" }, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
            <%= link_to "Home", { controller: "/home" } %>
            </li>
            <li>
            <a href="<%= request.protocol %><%= request.host_with_port %>/paginas/sobre">Sobre</a>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <%= yield %>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
              <li>
              <a href="https://github.com/Bastiani">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; RFDev 2015</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/paginas/_form.html.erb
<%= simple_form_for(@pagina) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :conteudo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/paginas/edit.html.erb
<h1>Editing pagina</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagina %> |
<%= link_to 'Back', paginas_path %>

app/views/paginas/index.html.erb
<h1>Listing paginas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paginas.each do |pagina| %>
      <tr>
        <td><%= pagina.titulo %></td>
        <td><%= pagina.conteudo %></td>
        <td><%= link_to 'Show', pagina %></td>
        <td><%= link_to 'Edit', edit_pagina_path(pagina) %></td>
        <td><%= link_to 'Destroy', pagina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pagina', new_pagina_path %>

app/views/paginas/new.html.erb
<h1>New pagina</h1>

<%= render 'form' %>

<%= link_to 'Back', paginas_path %>

app/views/paginas/show.html.erb
<% content_for :title do %>
  <%= @pagina.titulo %>
<% end %>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<% if @pagina.titulo == "Sobre" %>
  <header class="intro-header" style="background-image: url(<%= asset_path 'about-bg.jpg' %>)">
<% else %>
  <header class="intro-header" style="background-image: url(<%= asset_path 'paginas.jpg' %>)">
<% end %>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1><%= @pagina.titulo %></h1>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <%= @pagina.conteudo.html_safe %>
      </div>
    </div>
  </div>
</article>

app/views/posts/_form.html.erb
<%- model_class = Post -%>
<%= form_for @post, :html => { class: "form-horizontal post", style: "margin-top: 10px;" } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="container">
    <div class="form-group">
      <div class="row">
        <div class="col-sm-7">
          <%= f.label :titulo, :class => 'control-label' %>
          <%= f.text_field :titulo, :class => 'form-control' %>
          <%#=f.error_span(:titulo) %>
        </div>
        <div class="col-sm-7">
          <%= f.label :subtitulo, :class => 'control-label' %>
          <%= f.text_field :subtitulo, :class => 'form-control' %>
          <%#=f.error_span(:titulo) %>
        </div>
        <div class="col-sm-7">
          <%= f.label :img_titulo, :class => 'control-label' %>
          <%= f.text_field :img_titulo, :class => 'form-control' %>
          <%#=f.error_span(:titulo) %>
        </div>
        <div class="col-sm-7">
          <%#= f.label :texto, :class => 'control-label' %>
          <%= f.cktext_area :texto, :class => 'form_control', :ckeditor => {:toolbar => 'Full'} %>
          <%#=f.error_span(:texto) %>
          <%#= f.input :texto, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-5">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to "Cancelar", posts_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>RFDev</h1>
          <hr class="small">
          <span class="subheading">Programação, Linux e outros.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<% content_for :title do %>
  <%= @post.titulo %>
<% end %>
<% content_for :description do %>
  <%= @post.subtitulo %>
<% end %>

  <!-- Page Header -->
  <!-- Set your background image for this header on the line below. -->
  <header class="intro-header" style="background-image: url(<% if @post.img_titulo %><%= asset_path @post.img_titulo %><% else %><%= asset_path 'post-bg.jpg' %><% end %>)">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <div class="post-heading">
            <h1><%= @post.titulo %></h1>
            <h2 class="subheading"><%= @post.subtitulo %></h2>
            <span class="meta">Postado por <%= @post.user.name %> em <%= @post.created_at %></span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <%= @post.texto.html_safe %>
          <br />
          <!-- Go to www.addthis.com/dashboard to customize your tools -->
          <div class="addthis_sharing_toolbox"></div>
          <div id="disqus_thread"></div>
        </div>
      </div>
    </div>
  </article>

  <hr>
  <!-- Go to www.addthis.com/dashboard to customize your tools -->
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54b6fa6119280761" async="async"></script>
  <%= javascript_tag "
  hljs.configure({useBR: true});
  $('code').each(function(i, e) {hljs.highlightBlock(e)});

  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'rfdev'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
  " %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>